from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.banner, name='banner'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('pandas/', views.exam_result, name='pandas'),
    path('add-unit-data/', views.record_data, name='record-unit-data'),
    path('get-units/', views.get_units, name='get-units'),
    path('add-institute/', views.add_school, name='add-school'),
    path('show-institute/', views.show_institutes, name='show-institutes'),
    path('remove-institute/', views.remove_school, name='remove-school'),
    path('submit-and-add-more/', views.submit_and_add_more, name='submit-and-add-more'),
    path('add-cadet/', views.add_cadet, name='add-cadet'),
    path('cadet-list/', views.cadet_list, name='cadet-list'),
    path('remove-cadet/', views.remove_cadet, name='remove-cadet'),
    path('send-mail-cadets/', views.send_mail_cadets, name='send-mail-cadets'),
    path('schedule-exam/', views.schedule_exam, name='schedule-exam'),
    path('exam-batch-schedule/', views.exam_batch, name='exam-batch'),
    path('add-batch-data/', views.add_batch_data, name='add-batch-data'),
    path('batch-student-list/<int:batch>/', views.batch_student_list, name='batch-student-list'),
    path('send-exam-mail-cadets/', views.send_exam_mail_cadets, name='send-exam-mail-cadets'),
    path('add-exam-schedule/', views.add_exam_schedule, name='add-exam-schedule'),
    path('review-exam-schedule/', views.review_schedule, name='review-exam-schedule'),
    path('edit-exam-schedule/', views.edit_exam_schedule, name='edit-exam-schedule'),
    path('view-exam-result/', views.view_exam_result, name='view-exam-result'),
    path('wing-exam-result/<branch>/', views.wing_exam_result, name='wing-exam-result'),
    path('exam-result/', views.composite_result, name='exam-result'),
    path('exam-result-summary/', views.result_summary, name='exam-result-summary'),
    path('remove-batch/', views.remove_batch, name='remove-batch'),
    path('update-institute/<int:pk>/', views.SchoolEdit.as_view(), name='update-school'),
    path('update-cadet/<int:pk>/', views.cadet_edit, name='update-cadet'),
    path('detailed-result/<int:pk>/', views.detailed_result, name='detailed-result'),
    path('exam-result-pdf/<branch>/', views.print_exam_pdf, name='exam-result-pdf'),
    path('get-question/', views.get_question, name='get-question'),
    path('get-correct-ans/', views.get_correct_ans, name='get-correct-ans'),
    path('get-student-ans/', views.get_student_ans, name='get-student-ans'),
    path('form-as-list/', views.add_cadet_list, name='form-as-list'),

    ]