# Generated by Django 3.2.4 on 2021-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wing',
            field=models.CharField(choices=[('Army', 'Army'), ('Navy', 'Navy'), ('AF', 'AF')], default='Army', max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(default='Option number 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(default='Option number 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(default='Option number 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(default='Option number 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_5',
            field=models.CharField(default='Option number 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_6',
            field=models.CharField(default='Option number 1', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='Question number eYeKYAad', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Army', [('MR', 'MR'), ('Fd Craft/Battle Craft', 'Fd Craft/Battle Craft'), ('Mil History', 'Mil History'), ('Communication', 'Communication'), ('WE', 'WE')]), ('Navy', [('NO & GS', 'NO & GS'), ('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Seamanship', 'Seamanship'), ('FF, DC & SS', 'FF, DC & SS'), ('Ship & BM', 'Ship & BM'), ('Swimming', 'Swimming')]), ('Air', [('General Service', 'General Service'), ('Air Campaign', 'Air Campaign'), ('Pr of Flight', 'Pr of Flight'), ('Airmanship', 'Airmanship'), ('Navigation', 'Navigation'), ('Airframe', 'Airframe'), ('AeroModelling', 'AeroModelling')])], max_length=150),
        ),
    ]
