# Generated by Django 3.2.4 on 2021-06-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0004_auto_20210626_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('questions', models.CharField(max_length=150, verbose_name='Allotted Questions')),
                ('marks', models.CharField(max_length=150, verbose_name='Marks per question')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentscore',
            name='user',
        ),
    ]
