# Generated by Django 3.2.4 on 2021-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0005_auto_20210627_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='correct_answer',
            field=models.CharField(default='option_2', max_length=150),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='student_answer',
            field=models.CharField(default='option_1', max_length=150),
        ),
    ]
