# Generated by Django 3.2.4 on 2021-06-29 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_exam', '0006_auto_20210629_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
