# Generated by Django 3.2.4 on 2021-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0007_studentscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
