# Generated by Django 3.2.4 on 2021-06-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0008_studentscore_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschema',
            name='pass_percentage',
            field=models.IntegerField(default=40, max_length=150),
        ),
    ]
