# Generated by Django 3.2.4 on 2021-06-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0009_examschema_pass_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschema',
            name='pass_percentage',
            field=models.IntegerField(default=40),
        ),
    ]
