# Generated by Django 3.2.4 on 2021-07-03 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certexam', '0018_auto_20210701_2312'),
        ('online_exam', '0013_examschemasample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('Army', [('Armed Forces', 'Armed Forces'), ('MR', 'MR'), ('Fd Craft/Battle Craft', 'Fd Craft/Battle Craft'), ('Mil History', 'Mil History'), ('Communication', 'Communication'), ('WE', 'WE')]), ('Navy', [('NO & GS', 'NO & GS'), ('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Seamanship', 'Seamanship'), ('FF, DC & SS', 'FF, DC & SS'), ('Ship & BM', 'Ship & BM'), ('Swimming', 'Swimming')]), ('AF', [('General Service', 'General Service'), ('Air Campaign', 'Air Campaign'), ('Pr of Flight', 'Pr of Flight'), ('Airmanship', 'Airmanship'), ('Navigation', 'Navigation'), ('Airframe', 'Airframe'), ('AeroModelling', 'AeroModelling')])], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='samplequestion',
            name='subject',
            field=models.CharField(blank=True, choices=[('Army', [('Armed Forces', 'Armed Forces'), ('MR', 'MR'), ('Fd Craft/Battle Craft', 'Fd Craft/Battle Craft'), ('Mil History', 'Mil History'), ('Communication', 'Communication'), ('WE', 'WE')]), ('Navy', [('NO & GS', 'NO & GS'), ('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Seamanship', 'Seamanship'), ('FF, DC & SS', 'FF, DC & SS'), ('Ship & BM', 'Ship & BM'), ('Swimming', 'Swimming')]), ('AF', [('General Service', 'General Service'), ('Air Campaign', 'Air Campaign'), ('Pr of Flight', 'Pr of Flight'), ('Airmanship', 'Airmanship'), ('Navigation', 'Navigation'), ('Airframe', 'Airframe'), ('AeroModelling', 'AeroModelling')])], max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='CompliedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.CharField(blank=True, max_length=150, null=True)),
                ('marks_obtained', models.CharField(blank=True, max_length=150, null=True)),
                ('result', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('cadet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadet_compiled_result', to='certexam.cadet')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_compiled_result', to='certexam.cadet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_compiled_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
