# Generated by Django 3.2.12 on 2022-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0015_delete_compliedscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(blank=True, choices=[('Army', [('Armed Forces', 'Armed Forces'), ('MR', 'MR'), ('Fd Craft/Battle Craft', 'Fd Craft/Battle Craft'), ('Mil History', 'Mil History'), ('Communication', 'Communication'), ('WE', 'WE')]), ('Navy', [('NO & GS', 'NO & GS'), ('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Seamanship', 'Seamanship'), ('FF, DC & SS', 'FF, DC & SS'), ('Ship & BM', 'Ship & BM'), ('Swimming', 'Swimming')]), ('AF', [('General Service', 'General Service'), ('Air Campaign', 'Air Campaign'), ('Pr of Flight', 'Pr of Flight'), ('Airmanship', 'Airmanship'), ('Navigation', 'Navigation'), ('Aero Eng', 'Aero Eng'), ('BF Inst', 'BF Inst'), ('AeroModelling', 'AeroModelling')])], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='samplequestion',
            name='subject',
            field=models.CharField(blank=True, choices=[('Army', [('Armed Forces', 'Armed Forces'), ('MR', 'MR'), ('Fd Craft/Battle Craft', 'Fd Craft/Battle Craft'), ('Mil History', 'Mil History'), ('Communication', 'Communication'), ('WE', 'WE')]), ('Navy', [('NO & GS', 'NO & GS'), ('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Seamanship', 'Seamanship'), ('FF, DC & SS', 'FF, DC & SS'), ('Ship & BM', 'Ship & BM'), ('Swimming', 'Swimming')]), ('AF', [('General Service', 'General Service'), ('Air Campaign', 'Air Campaign'), ('Pr of Flight', 'Pr of Flight'), ('Airmanship', 'Airmanship'), ('Navigation', 'Navigation'), ('Aero Eng', 'Aero Eng'), ('BF Inst', 'BF Inst'), ('AeroModelling', 'AeroModelling')])], max_length=150, null=True),
        ),
    ]
