# Generated by Django 3.2.4 on 2021-06-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0002_cadet_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='gender',
            field=models.CharField(default='Male', max_length=150),
            preserve_default=False,
        ),
    ]
