# Generated by Django 3.2.4 on 2021-06-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0003_cadet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='wing',
            field=models.CharField(default='Army', max_length=150),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='gender',
            field=models.CharField(default='Male', max_length=150),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='sec_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
    ]
