# Generated by Django 3.2.4 on 2021-06-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0004_auto_20210625_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='wing',
            field=models.CharField(default='Army', max_length=150),
        ),
    ]
