# Generated by Django 3.2.4 on 2021-06-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certexam', '0005_school_wing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='unit',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150)),
                ('strength', models.CharField(max_length=150)),
                ('batch', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
