# Generated by Django 3.2.4 on 2021-06-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0006_auto_20210625_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadet_email', to='certexam.cadet')),
            ],
        ),
    ]
