# Generated by Django 3.2.4 on 2021-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0007_emailrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
