# Generated by Django 3.2.4 on 2021-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0008_auto_20210625_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
