# Generated by Django 3.2.4 on 2021-06-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0009_examschedule_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='battalion',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
