# Generated by Django 3.2.4 on 2021-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0010_auto_20210626_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='standard',
            field=models.CharField(default=12, max_length=150),
        ),
    ]
