# Generated by Django 3.2.4 on 2021-06-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0011_cadet_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_email', to='certexam.examschedule'),
        ),
    ]
