# Generated by Django 3.2.4 on 2021-06-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0012_emailrecord_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='from_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='from_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='meet',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
