# Generated by Django 3.2.4 on 2021-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0014_rename_from_to_emailrecord_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='appeared',
            field=models.BooleanField(default=False),
        ),
    ]
