# Generated by Django 3.2.4 on 2021-06-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0015_cadet_appeared'),
    ]

    operations = [
        migrations.AddField(
            model_name='battalion',
            name='wing',
            field=models.CharField(default='Army', max_length=150),
        ),
    ]
