# Generated by Django 3.2.4 on 2021-06-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0016_battalion_wing'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='appeared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
