# Generated by Django 3.2.4 on 2021-07-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0019_compliedscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliedscore',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_compiled_result', to='certexam.school'),
        ),
    ]
