# Generated by Django 3.2.12 on 2022-03-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certexam', '0020_alter_compliedscore_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliedscore',
            options={'ordering': ['-percentage']},
        ),
    ]
